### ISSUE TITLE
design choice on pitch shift 

### ISSUE THREAD

**Issue by keunwoochoi** [Spijkervet/audio-augmentations#6]
Why does `PitchShift()` change the length of the input audio? Wouldn't it make more sense to preserve the shape in this transform?

**Comment by Spijkervet** [comment]
This is odd behavior I noticed in the underlying sox calls that PitchShift() is making to the WavAugment library. I believe the code in https://github.com/Spijkervet/torchaudio-augmentations/blob/master/torchaudio_augmentations/augmentations/pitch_shift.py#L33 should preserve the actual input shapes.

Since this is the fastest pitch shifting implementation, I'm sticking with this hacky fix until we find a faster alternative.

**Comment by keunwoochoi** [comment]
But your module wraps their function. How about adding shape matching after calling WavAugment?

**Comment by Spijkervet** [comment]
The pitch shift module was replaced with `torch-pitch-shift` as per https://github.com/Spijkervet/torchaudio-augmentations/commit/9d4943bf8ae62ffea6b6839e78931e8054df0e3e - the shape matching tests are included in `./tests/test_augmentations.py`
